def helpscrn():
    print()
    print(" ----------------- HELP ----------------")
    print("HELP - View list of isntructions.")
    print("CLS - Clear the screen.")
    print("DIR - List files and folders in current folder/directory.")
    print("CD <foldername> - To navigate to a subfolder.")
    print("CD .. - To navigate to the parent folder.")
    print("MKDIR <foldername> - To create a subfolder.")
    print("RENAME <name> <newname> - To rename a subfolder or a file.")
    print("DEL <name> - To delete a subfolder or a file.")
    print("ECHO <message> - Displays a message.")
    print("TIME - Shows the current time.")
    print("DATE - Shows the current date.")
    print("REBOOT - Reboots PyDOS.")
    print("EXIT - Quit.")
    print(" ---------------------------------------")
